### ISSUE TITLE
Fix logic issue in setting of the $zman_BROWSER variable

### ISSUE THREAD

**Issue by Leonardo-Gerling** [mattmc3/zdocs#1]
If you specify `$BROWSER`, `$zman_BROWSER` will not be that variable, because of the usage of `[[ -z ]]` [explanation here](https://stackoverflow.com/questions/3869072/test-for-non-zero-length-string-in-bash-n-var-or-var).
Instead it will be one of the other options, for me it was `xdg-open`. 
However, if you don't specify `$BROWSER`, the first condition will be true and `$zman_BROWSER=""`, which will throw an error, because you just execute the link.

What you wanted to do is probably this:
`if [[ -n "$BROWSER" ]] ...`

**Comment by mattmc3** [comment]
@Leonardo-Gerling thank you! Great catch. I've committed a fix.
